"""Add saved_file_name to TranscriptionJob

Revision ID: 2456d404d7ad
Revises: 5a701ead2002
Create Date: 2026-01-22 03:57:49.738685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2456d404d7ad'
down_revision = '5a701ead2002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_jobs', sa.Column('saved_file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription_jobs', 'saved_file_name')
    # ### end Alembic commands ###
