"""Add CANCELLED status to TranscriptionJobStatus enum

Revision ID: 2d68d0ce676d
Revises: e898fb5ba053
Create Date: 2026-01-22 03:56:45.152716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d68d0ce676d'
down_revision = 'e898fb5ba053'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TYPE transcriptionjobstatus ADD VALUE 'CANCELLED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
