"""Add collection, source_transcription_id, and document_type to Document model

Revision ID: 408a3406f8f4
Revises: d218220c25d5
Create Date: 2026-01-26 09:51:00.723627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408a3406f8f4'
down_revision = 'd218220c25d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('collection', sa.String(), nullable=True))
    op.execute("UPDATE documents SET collection = 'corporate' WHERE collection IS NULL")
    op.alter_column('documents', 'collection',
               existing_type=sa.String(),
               nullable=False,
               existing_nullable=True,
               server_default='corporate')

    op.add_column('documents', sa.Column('source_transcription_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('document_type', sa.String(), nullable=True))
    op.create_foreign_key('fk_documents_transcription_jobs_source_transcription_id', 'documents', 'transcription_jobs', ['source_transcription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'source_transcription_id')
    op.drop_column('documents', 'collection')
    # ### end Alembic commands ###
