"""Add TranscriptionJob table

Revision ID: 5406537889f9
Revises: 6fd92caaedc8
Create Date: 2026-01-21 10:51:57.252424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5406537889f9'
down_revision = '6fd92caaedc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='transcriptionjobstatus'), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('progress_text', sa.String(), nullable=True),
    sa.Column('full_transcript', sa.Text(), nullable=True),
    sa.Column('meeting_minutes', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcription_jobs')
    # ### end Alembic commands ###
