"""Add celery_task_id to TranscriptionJob

Revision ID: 5a701ead2002
Revises: 2d68d0ce676d
Create Date: 2026-01-22 03:57:07.501518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a701ead2002'
down_revision = '2d68d0ce676d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_jobs', sa.Column('celery_task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription_jobs', 'celery_task_id')
    # ### end Alembic commands ###
