"""Make meeting_name non-nullable in transcription_jobs

Revision ID: 9f00839ad62e
Revises: fc53d6cf6904
Create Date: 2026-01-27 06:55:37.205273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f00839ad62e'
down_revision = 'fc53d6cf6904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update existing NULL values to avoid an integrity error.
    op.execute('UPDATE transcription_jobs SET meeting_name = original_filename WHERE meeting_name IS NULL')
    
    # Now, apply the NOT NULL constraint.
    op.alter_column('transcription_jobs', 'meeting_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transcription_jobs', 'meeting_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
