"""Add cascade delete to documents from transcription_jobs

Revision ID: c09afb93a7fb
Revises: 9f00839ad62e
Create Date: 2026-01-27 07:31:05.048756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09afb93a7fb'
down_revision = '9f00839ad62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_documents_transcription_jobs_source_transcription_id'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'transcription_jobs', ['source_transcription_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_transcription_jobs_source_transcription_id'), 'documents', 'transcription_jobs', ['source_transcription_id'], ['id'])
    # ### end Alembic commands ###
