"""add meeting_name to transcriptionjob

Revision ID: d218220c25d5
Revises: 2456d404d7ad
Create Date: 2026-01-23 07:53:04.341192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd218220c25d5'
down_revision = '2456d404d7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_jobs', sa.Column('meeting_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription_jobs', 'meeting_name')
    # ### end Alembic commands ###
