"""Add TranscriptionJob table

Revision ID: e898fb5ba053
Revises: 5406537889f9
Create Date: 2026-01-21 11:10:25.005539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e898fb5ba053'
down_revision = '5406537889f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
