"""Add collection to Chat model

Revision ID: fc53d6cf6904
Revises: 408a3406f8f4
Create Date: 2026-01-26 11:28:44.796467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc53d6cf6904'
down_revision = '408a3406f8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('collection', sa.String(), nullable=True))
    op.execute("UPDATE chats SET collection = 'corporate' WHERE collection IS NULL")
    op.alter_column('chats', 'collection',
               existing_type=sa.String(),
               nullable=False,
               existing_nullable=True,
               server_default='corporate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'collection')
    # ### end Alembic commands ###
